/**
 * Classify every drill in the corpus and write the result to
 * `src/data/drillTags.ts`.
 *
 * Run: `npm run tag-drills` — after adding or editing a drill.
 *
 * The corpus is static, so the tags are generated once and committed rather
 * than recomputed on every page load. The classification itself lives in
 * `@/lib/drillTags`, where it is tested; this file only walks the corpus and
 * writes the file.
 */

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { corpus } from '../src/data/corpus'
import { tagDrill } from '../src/lib/drillTags'

const OUTPUT = fileURLToPath(new URL('../src/data/drillTags.ts', import.meta.url))

const entries = corpus.map((drill) => [drill.id, tagDrill(drill.km)] as const)

const header = `/**
 * Generated by \`scripts/tag-drills.ts\` — do not edit by hand.
 *
 * What each drill contains and roughly how hard it is, keyed by drill id. The
 * corpus does not change between deploys, so this is committed rather than
 * computed at page load. Re-run \`npm run tag-drills\` after touching the
 * corpus; a drill with no entry here is one nobody tagged.
 */

import type { DrillTags } from '@/lib/drillTags'

export const drillTags: Record<string, DrillTags> = {
`

const body = entries
  .map(([id, tags]) => `  ${id}: ${JSON.stringify(tags)},`)
  .join('\n')

writeFileSync(OUTPUT, `${header}${body}\n}\n`)

/*
 * A short profile on stdout, because the numbers are the point: the v3 plan was
 * written off exactly this shape, and a corpus that has quietly stopped having
 * a shallow end should say so out loud.
 */
const withoutCoeng = entries.filter(([, tags]) => !tags.features.includes('subscriptConsonant'))
const plainConsonants = entries.filter(
  ([, tags]) => tags.features.length === 1 && tags.features[0] === 'baseConsonant',
)
const consonants = new Set(entries.flatMap(([, tags]) => tags.consonants))

console.log(`${entries.length} drills tagged → ${OUTPUT}`)
console.log(`  no stacking:        ${withoutCoeng.length}`)
console.log(`  base consonants only: ${plainConsonants.length}`)
console.log(`  distinct consonants used: ${consonants.size} of 33`)
